apiVersion: v2
name: cert-manager-webhook-pdns
version: 2.0.1
description: Cert Manager Webhook for PowerDNS.
type: application
home: https://github.com/zachomedia/cert-manager-webhook-pdns
maintainers:
  - name: Zachary Seguin
    email: zachary@zacharyseguin.ca
    url: https://zacharyseguin.ca
appVersion: v2.0.1
